export const subjectUnitDisplayNameMap: Record<string, string> = {
  "IT_WINDOWS": "パソコン操作（Windows）",
  "IT_IPAD": "タブレット操作（iPad）",
  "IT_CHROMEBOOK": "タブレット操作（Chromebook）",
  "IT_INTERNET": "スマホ・ネット",
  "IT_LITERACY": "情報リテラシー",
  "IT_PROGRAMMING": "プログラミング",
  "IT_SECURITY": "モラル・セキュリティ",
  "MAP_SYMBOLS": "地図記号",
  "PREFECTURES": "都道府県",
  "PREF_CAPITALS": "県庁所在地",
  "KOKUGO_G1_U01": "ひらがな",
  "KOKUGO_G1_U02": "ことばあつめ",
  "KOKUGO_G1_U03": "のばすおん（ー）",
  "KOKUGO_G1_U04": "ちいさい「っ」",
  "KOKUGO_G1_U05": "「は・を・へ」のつかいかた",
  "KOKUGO_G1_U06": "かたかな",
  "KOKUGO_G1_U07": "おはなしをよむ",
  "KOKUGO_G1_U08": "せつめいぶんをよむ",
  "KOKUGO_G1_U09": "ばめんをそうぞうしてよむ",
  "KOKUGO_G1_U10": "たいせつなところをみつけてよむ",
  "KOKUGO_G1_U11": "ぶんをかく",
  "KOKUGO_G1_U12": "かんたんなにっき",
  "KOKUGO_G1_U13": "おはなしをつくる",
  "KOKUGO_G1_U14": "はなしをきく",
  "KOKUGO_G1_U15": "じぶんのことをはなす",
  "KOKUGO_G1_U16": "みんなのまえではなす",
  "KOKUGO_G2_U01": "かたかなのことば",
  "KOKUGO_G2_U02": "主語 と 述語",
  "KOKUGO_G2_U03": "文のきまり",
  "KOKUGO_G2_U04": "日記を書く",
  "KOKUGO_G2_U05": "せつめい文を読む",
  "KOKUGO_G2_U06": "物語を読む",
  "KOKUGO_G2_U07": "大事なことを見つける",
  "KOKUGO_G2_U08": "手紙を書く",
  "KOKUGO_G2_U09": "作文を書く",
  "KOKUGO_G2_U10": "話を聞く",
  "KOKUGO_G2_U11": "順序よく話す",
  "KOKUGO_G3_U01": "漢字の読み書き",
  "KOKUGO_G3_U02": "国語辞典の使い方",
  "KOKUGO_G3_U03": "段落",
  "KOKUGO_G3_U04": "物語文の読み取り",
  "KOKUGO_G3_U05": "説明文の読み取り",
  "KOKUGO_G3_U06": "要点をまとめる",
  "KOKUGO_G3_U07": "日記・作文",
  "KOKUGO_G3_U08": "手紙の書き方",
  "KOKUGO_G3_U09": "話し合い",
  "KOKUGO_G4_U01": "漢字の使い方",
  "KOKUGO_G4_U02": "熟語",
  "KOKUGO_G4_U03": "国語辞典・漢字辞典",
  "KOKUGO_G4_U04": "段落と要旨",
  "KOKUGO_G4_U05": "物語文の読み取り",
  "KOKUGO_G4_U06": "説明文の読み取り",
  "KOKUGO_G4_U07": "要約",
  "KOKUGO_G4_U08": "意見文を書く",
  "KOKUGO_G4_U09": "話し合いと発表",
  "KOKUGO_G5_U01": "漢字の意味と使い分け",
  "KOKUGO_G5_U02": "敬語",
  "KOKUGO_G5_U03": "物語文の読み取り",
  "KOKUGO_G5_U04": "説明文の読み取り",
  "KOKUGO_G5_U05": "要約と要旨",
  "KOKUGO_G5_U06": "意見文を書く",
  "KOKUGO_G5_U07": "報告文を書く",
  "KOKUGO_G5_U08": "討論",
  "KOKUGO_G5_U09": "スピーチ",
  "KOKUGO_G6_U01": "漢字のまとめ",
  "KOKUGO_G6_U02": "熟語と語句",
  "KOKUGO_G6_U03": "物語文の読み取り",
  "KOKUGO_G6_U04": "説明文の読み取り",
  "KOKUGO_G6_U05": "要旨と要約",
  "KOKUGO_G6_U06": "意見文を書く",
  "KOKUGO_G6_U07": "提案文を書く",
  "KOKUGO_G6_U08": "討論",
  "KOKUGO_G6_U09": "スピーチ",
  "KOKUGO_G6_U10": "卒業文集",
  "KOKUGO_G7_U01": "物語文の読み取り",
  "KOKUGO_G7_U02": "説明文の読み取り",
  "KOKUGO_G7_U03": "詩の読み取り",
  "KOKUGO_G7_U04": "古典（古文の基礎）",
  "KOKUGO_G7_U05": "漢文の基礎",
  "KOKUGO_G7_U06": "文の成分（主語・述語など）",
  "KOKUGO_G7_U07": "品詞",
  "KOKUGO_G7_U08": "漢字の読み書き",
  "KOKUGO_G7_U09": "要約",
  "KOKUGO_G7_U10": "意見文",
  "KOKUGO_G7_U11": "スピーチ",
  "KOKUGO_G7_U12": "話し合い",
  "KOKUGO_G8_U01": "物語文の読み取り",
  "KOKUGO_G8_U02": "説明文の読み取り",
  "KOKUGO_G8_U03": "詩・短歌・俳句",
  "KOKUGO_G8_U04": "古文（物語・随筆）",
  "KOKUGO_G8_U05": "漢文（訓読・故事成語）",
  "KOKUGO_G8_U06": "文法（品詞・活用）",
  "KOKUGO_G8_U07": "漢字の読み書き",
  "KOKUGO_G8_U08": "要約",
  "KOKUGO_G8_U09": "意見文",
  "KOKUGO_G8_U10": "発表",
  "KOKUGO_G8_U11": "討論",
  "KOKUGO_G9_U01": "物語文の読み取り",
  "KOKUGO_G9_U02": "説明文の読み取り",
  "KOKUGO_G9_U03": "詩・短歌・俳句",
  "KOKUGO_G9_U04": "古文（古典文学）",
  "KOKUGO_G9_U05": "漢文（名文・思想）",
  "KOKUGO_G9_U06": "文法（文の構造）",
  "KOKUGO_G9_U07": "漢字の読み書き",
  "KOKUGO_G9_U08": "要約",
  "KOKUGO_G9_U09": "論説文を書く",
  "KOKUGO_G9_U10": "スピーチ",
  "KOKUGO_G9_U11": "討論",
  "KOKUGO_G9_U12": "卒業論文・発表",
  "MATH_G1_U01": "かずとすうじ（10までの かず）",
  "MATH_G1_U02": "いくつといくつ",
  "MATH_G1_U03": "かたちあそび",
  "MATH_G1_U04": "なんばんめ",
  "MATH_G1_U05": "あわせていくつ（たしざん）",
  "MATH_G1_U06": "ふえるといくつ（たしざん）",
  "MATH_G1_U07": "のこりはいくつ（ひきざん）",
  "MATH_G1_U08": "ちがいはいくつ（ひきざん）",
  "MATH_G1_U09": "20までのかず",
  "MATH_G1_U10": "なんじ（とけい）",
  "MATH_G1_U11": "ながさくらべ",
  "MATH_G1_U12": "かさくらべ",
  "MATH_G1_U13": "えぐらふ",
  "MATH_G1_U14": "ひょう",
  "MATH_G1_U15": "さんかくとしかく",
  "MATH_G1_U16": "かたちづくり",
  "MATH_G1_U17": "3つのかずのけいさん",
  "MATH_G1_U18": "ぶんしょうだい",
  "MATH_G2_U01": "表 と グラフ",
  "MATH_G2_U02": "たし算（2けた＋2けた）",
  "MATH_G2_U03": "ひき算（2けた−2けた）",
  "MATH_G2_U04": "長さ（ものさし）",
  "MATH_G2_U05": "100までの 数",
  "MATH_G2_U06": "かさ（リットル・デシリットル）",
  "MATH_G2_U07": "時こく と 時かん",
  "MATH_G2_U08": "3けたの 数",
  "MATH_G2_U09": "かけ算（かけ算のいみ）",
  "MATH_G2_U10": "かけ算（九九）",
  "MATH_G2_U11": "はこの 形",
  "MATH_G2_U12": "ぶんしょうだい",
  "MATH_G2_U13": "かけ算 1のだん",
  "MATH_G2_U14": "かけ算 2のだん",
  "MATH_G2_U15": "かけ算 3のだん",
  "MATH_G2_U16": "かけ算 4のだん",
  "MATH_G2_U17": "かけ算 5のだん",
  "MATH_G2_U18": "かけ算 6のだん",
  "MATH_G2_U19": "かけ算 7のだん",
  "MATH_G2_U20": "かけ算 8のだん",
  "MATH_G2_U21": "かけ算 9のだん",
  "MATH_G3_U01": "表 と グラフ",
  "MATH_G3_U02": "大きい 数（1000より大きい数）",
  "MATH_G3_U03": "たし算（3けた・4けた）",
  "MATH_G3_U04": "ひき算（3けた・4けた）",
  "MATH_G3_U05": "時こく と 時かん",
  "MATH_G3_U06": "長さ（km と m）",
  "MATH_G3_U07": "かけ算（2けた×1けた など）",
  "MATH_G3_U08": "円 と きゅう",
  "MATH_G3_U09": "わり算（わり算のいみ）",
  "MATH_G3_U10": "わり算（あまりのある計算）",
  "MATH_G3_U11": "重さ（g と kg）",
  "MATH_G3_U12": "小数",
  "MATH_G3_U13": "分数",
  "MATH_G3_U14": "□をつかった 式",
  "MATH_G4_U01": "大きい 数（1おくまでの数）",
  "MATH_G4_U02": "わり算（2けたでわる計算）",
  "MATH_G4_U03": "折れ線グラフ",
  "MATH_G4_U04": "角",
  "MATH_G4_U05": "そろばん",
  "MATH_G4_U06": "小数",
  "MATH_G4_U07": "小数の たし算 と ひき算",
  "MATH_G4_U08": "面せき",
  "MATH_G4_U09": "がい数",
  "MATH_G4_U10": "式 と 計算の じゅんじょ",
  "MATH_G4_U11": "分数",
  "MATH_G4_U12": "分数の たし算 と ひき算",
  "MATH_G4_U13": "直方体 と 立方体",
  "MATH_G4_U14": "変わり方",
  "MATH_G4_U15": "調べたことを 表 や グラフ にまとめる",
  "MATH_G5_U01": "整数 と 小数",
  "MATH_G5_U02": "体積",
  "MATH_G5_U03": "小数の かけ算",
  "MATH_G5_U04": "小数の わり算",
  "MATH_G5_U05": "合同な 図形",
  "MATH_G5_U06": "分数 と 小数・整数",
  "MATH_G5_U07": "分数の たし算 と ひき算",
  "MATH_G5_U08": "平均",
  "MATH_G5_U09": "単位量あたりの 大きさ",
  "MATH_G5_U10": "速さ",
  "MATH_G5_U11": "比例",
  "MATH_G5_U12": "円 と 正多角形",
  "MATH_G5_U13": "角柱 と 円柱",
  "MATH_G5_U14": "割合",
  "MATH_G5_U15": "帯グラフ と 円グラフ",
  "MATH_G6_U01": "対称な 図形",
  "MATH_G6_U02": "文字 と 式",
  "MATH_G6_U03": "分数の かけ算",
  "MATH_G6_U04": "分数の わり算",
  "MATH_G6_U05": "比 と その 利用",
  "MATH_G6_U06": "比例 と 反比例",
  "MATH_G6_U07": "拡大図 と 縮図",
  "MATH_G6_U08": "円の 面積",
  "MATH_G6_U09": "角柱 と 円柱の 体積",
  "MATH_G6_U10": "およその 面積 と 体積",
  "MATH_G6_U11": "場合の 数",
  "MATH_G6_U12": "資料の 調べ方",
  "MATH_G6_U13": "算数の まとめ",
  "MATH_G7_U01": "正の数 と 負の数",
  "MATH_G7_U02": "正負の数の 加法 と 減法",
  "MATH_G7_U03": "正負の数の 乗法 と 除法",
  "MATH_G7_U04": "文字式",
  "MATH_G7_U05": "文字式の 計算",
  "MATH_G7_U06": "一次方程式",
  "MATH_G7_U07": "一次方程式の 利用",
  "MATH_G7_U08": "比例 と 反比例",
  "MATH_G7_U09": "平面図形",
  "MATH_G7_U10": "空間図形",
  "MATH_G7_U11": "資料の 整理 と 活用",
  "MATH_G8_U01": "式の計算",
  "MATH_G8_U02": "連立方程式",
  "MATH_G8_U03": "連立方程式の 利用",
  "MATH_G8_U04": "一次関数",
  "MATH_G8_U05": "図形の 性質",
  "MATH_G8_U06": "図形の 合同",
  "MATH_G8_U07": "三角形 と 四角形",
  "MATH_G8_U08": "確率",
  "MATH_G8_U09": "データの 分析",
  "MATH_G9_U01": "式の 展開 と 因数分解",
  "MATH_G9_U02": "平方根",
  "MATH_G9_U03": "二次方程式",
  "MATH_G9_U04": "二次方程式の 利用",
  "MATH_G9_U05": "関数 y=ax²",
  "MATH_G9_U06": "相似な 図形",
  "MATH_G9_U07": "三平方の 定理",
  "MATH_G9_U08": "円の 性質",
  "MATH_G9_U09": "標本調査",
  "ENGLISH_G3_U01": "あいさつ",
  "ENGLISH_G3_U02": "じこしょうかい",
  "ENGLISH_G3_U03": "すきなもの",
  "ENGLISH_G3_U04": "かぞく",
  "ENGLISH_G3_U05": "いろ",
  "ENGLISH_G3_U06": "かず（1〜20）",
  "ENGLISH_G3_U07": "どうぶつ",
  "ENGLISH_G3_U08": "くだもの・たべもの",
  "ENGLISH_G3_U09": "きぶん",
  "ENGLISH_G3_U10": "からだのぶぶん",
  "ENGLISH_G3_U11": "リスニング総仕上げ",
  "ENGLISH_G3_U12": "発声総仕上げ",
  "ENGLISH_G3_U13": "復唱問題総仕上げ",
  "ENGLISH_G3_U14": "応答問題総仕上げ",
  "ENGLISH_G4_U01": "あいさつと会話",
  "ENGLISH_G4_U02": "すきな教科",
  "ENGLISH_G4_U03": "一日の生活",
  "ENGLISH_G4_U04": "天気",
  "ENGLISH_G4_U05": "時こく",
  "ENGLISH_G4_U06": "文ぼうぐ",
  "ENGLISH_G4_U07": "場所",
  "ENGLISH_G4_U08": "学校の中",
  "ENGLISH_G4_U09": "すきな食べ物",
  "ENGLISH_G4_U10": "日本の文化しょうかい",
  "ENGLISH_G4_U11": "リスニング総仕上げ",
  "ENGLISH_G4_U12": "発声総仕上げ",
  "ENGLISH_G4_U13": "復唱問題総仕上げ",
  "ENGLISH_G4_U14": "応答問題総仕上げ",
  "ENGLISH_G5_U01": "アルファベット",
  "ENGLISH_G5_U02": "自己紹介",
  "ENGLISH_G5_U03": "家族",
  "ENGLISH_G5_U04": "誕生日",
  "ENGLISH_G5_U05": "好きなもの",
  "ENGLISH_G5_U06": "学校生活",
  "ENGLISH_G5_U07": "曜日",
  "ENGLISH_G5_U08": "時こく",
  "ENGLISH_G5_U09": "できること（can）",
  "ENGLISH_G5_U10": "行きたい場所",
  "ENGLISH_G5_U11": "リスニング総仕上げ",
  "ENGLISH_G5_U12": "発声総仕上げ",
  "ENGLISH_G5_U13": "復唱問題総仕上げ",
  "ENGLISH_G5_U14": "応答問題総仕上げ",
  "ENGLISH_G6_U01": "自己紹介",
  "ENGLISH_G6_U02": "将来の夢",
  "ENGLISH_G6_U03": "日常生活",
  "ENGLISH_G6_U04": "日本文化紹介",
  "ENGLISH_G6_U05": "行きたい国",
  "ENGLISH_G6_U06": "思い出",
  "ENGLISH_G6_U07": "過去の出来事",
  "ENGLISH_G6_U08": "好きなもの",
  "ENGLISH_G6_U09": "世界の文化",
  "ENGLISH_G6_U10": "将来の計画",
  "ENGLISH_G6_U11": "リスニング総仕上げ",
  "ENGLISH_G6_U12": "発声総仕上げ",
  "ENGLISH_G6_U13": "復唱問題総仕上げ",
  "ENGLISH_G6_U14": "応答問題総仕上げ",
  "ENGLISH_G7_U01": "アルファベット",
  "ENGLISH_G7_U02": "be動詞",
  "ENGLISH_G7_U03": "一般動詞",
  "ENGLISH_G7_U04": "疑問文",
  "ENGLISH_G7_U05": "否定文",
  "ENGLISH_G7_U06": "命令文",
  "ENGLISH_G7_U07": "can",
  "ENGLISH_G7_U08": "現在進行形",
  "ENGLISH_G7_U09": "三人称単数",
  "ENGLISH_G7_U10": "前置詞",
  "ENGLISH_G7_U11": "複数形",
  "ENGLISH_G7_U12": "代名詞",
  "ENGLISH_G7_U13": "リスニング総仕上げ",
  "ENGLISH_G7_U14": "発声総仕上げ",
  "ENGLISH_G7_U15": "復唱問題総仕上げ",
  "ENGLISH_G7_U16": "応答問題総仕上げ",
  "ENGLISH_G8_U01": "過去形",
  "ENGLISH_G8_U02": "過去進行形",
  "ENGLISH_G8_U03": "未来表現（will / be going to）",
  "ENGLISH_G8_U04": "助動詞（must / have to / may など）",
  "ENGLISH_G8_U05": "不定詞",
  "ENGLISH_G8_U06": "動名詞",
  "ENGLISH_G8_U07": "接続詞",
  "ENGLISH_G8_U08": "比較（比較級・最上級）",
  "ENGLISH_G8_U09": "受動態",
  "ENGLISH_G8_U10": "リスニング総仕上げ",
  "ENGLISH_G8_U11": "発声総仕上げ",
  "ENGLISH_G8_U12": "復唱問題総仕上げ",
  "ENGLISH_G8_U13": "応答問題総仕上げ",
  "ENGLISH_G9_U01": "現在完了",
  "ENGLISH_G9_U02": "現在完了進行形",
  "ENGLISH_G9_U03": "関係代名詞",
  "ENGLISH_G9_U04": "間接疑問文",
  "ENGLISH_G9_U05": "仮定法",
  "ENGLISH_G9_U06": "分詞",
  "ENGLISH_G9_U07": "比較の応用",
  "ENGLISH_G9_U08": "長文読解",
  "ENGLISH_G9_U09": "英作文",
  "ENGLISH_G9_U10": "スピーチ",
  "ENGLISH_G9_U11": "リスニング総仕上げ",
  "ENGLISH_G9_U12": "発声総仕上げ",
  "ENGLISH_G9_U13": "復唱問題総仕上げ",
  "ENGLISH_G9_U14": "応答問題総仕上げ",
  "LIFE_1_1": "1年生活（通年）",
  "LIFE_2_1": "2年生活（通年）",
  "SCIENCE_3_1": "3年理科（1学期）",
  "SCIENCE_3_2": "3年理科（2学期）",
  "SCIENCE_3_3": "3年理科（3学期）",
  "SCIENCE_4_1": "4年理科（1学期）",
  "SCIENCE_4_2": "4年理科（2学期）",
  "SCIENCE_4_3": "4年理科（3学期）",
  "SCIENCE_5_1": "5年理科（1学期）",
  "SCIENCE_5_2": "5年理科（2学期）",
  "SCIENCE_5_3": "5年理科（3学期）",
  "SCIENCE_6_1": "6年理科（1学期）",
  "SCIENCE_6_2": "6年理科（2学期）",
  "SCIENCE_6_3": "6年理科（3学期）",
  "SOCIAL_3_1": "3年社会",
  "SOCIAL_4_1": "4年社会",
  "SOCIAL_5_1": "5年社会",
  "SOCIAL_6_1": "6年社会",
  "SOCIAL_7_1": "7年社会（中学1年）",
  "SOCIAL_8_1": "8年社会（中学2年）",
  "SOCIAL_9_1": "9年社会（中学3年）",
};

const SUBJECT_PREFIX_LABELS: Record<string, string> = {
  MATH: '算数・数学',
  KOKUGO: '国語',
  ENGLISH: '英語',
  LIFE: '生活',
  SCIENCE: '理科',
  SOCIAL: '社会',
  IT: 'IT・情報',
  MAP: '地図',
  PREF: '地図',
  KANJI: '漢字',
};

const formatUnitKeyFallback = (unitKey: string) => {
  const parts = unitKey.split('_');
  if (parts.length >= 2) {
    const subject = SUBJECT_PREFIX_LABELS[parts[0]] || parts[0];
    const grade = Number(parts[1]);
    const gradeLabel = Number.isFinite(grade)
      ? (grade <= 6 ? `小${grade}` : `中${grade - 6}`)
      : parts[1];
    const unitNo = parts.find((part) => /^U\d+$/i.test(part));
    return `${subject} ${gradeLabel}${unitNo ? ` ${unitNo.replace(/^U/i, '単元')}` : ''}`;
  }
  return unitKey.replaceAll('_', ' ');
};

export const getSubjectUnitDisplayName = (unitKey: string): string =>
  subjectUnitDisplayNameMap[unitKey] || formatUnitKeyFallback(unitKey);
