export interface ScienceUnitOption {
  id: string;
  name: string;
  mode: string;
  sourceMode: string;
}

export const SCIENCE_GRADE_UNITS: Record<number, ScienceUnitOption[]> = {
  1: [
    { id: 'L1_U01', name: 'がっこうたんけん', mode: 'LIFE_1_U01', sourceMode: 'LIFE_1_1' },
    { id: 'L1_U02', name: 'がっこうのひととなかよし', mode: 'LIFE_1_U02', sourceMode: 'LIFE_1_1' },
    { id: 'L1_U03', name: 'きせつとなかよし', mode: 'LIFE_1_U03', sourceMode: 'LIFE_1_2' },
    { id: 'L1_U04', name: 'いきものとなかよし', mode: 'LIFE_1_U04', sourceMode: 'LIFE_1_1' },
    { id: 'L1_U05', name: 'はなややさいをそだてよう', mode: 'LIFE_1_U05', sourceMode: 'LIFE_1_1' },
    { id: 'L1_U06', name: 'みぢかなものあそび', mode: 'LIFE_1_U06', sourceMode: 'LIFE_1_2' },
    { id: 'L1_U07', name: 'じぶんのせいちょう', mode: 'LIFE_1_U07', sourceMode: 'LIFE_1_3' },
  ],
  2: [
    { id: 'L2_U01', name: 'まちたんけん', mode: 'LIFE_2_U01', sourceMode: 'LIFE_2_1' },
    { id: 'L2_U02', name: 'まちのひととなかよし', mode: 'LIFE_2_U02', sourceMode: 'LIFE_2_1' },
    { id: 'L2_U03', name: 'きせつのしぜん', mode: 'LIFE_2_U03', sourceMode: 'LIFE_2_2' },
    { id: 'L2_U04', name: 'やさいをそだてよう', mode: 'LIFE_2_U04', sourceMode: 'LIFE_2_1' },
    { id: 'L2_U05', name: 'いきもののかんさつ', mode: 'LIFE_2_U05', sourceMode: 'LIFE_2_2' },
    { id: 'L2_U06', name: 'おもちゃづくり', mode: 'LIFE_2_U06', sourceMode: 'LIFE_2_2' },
    { id: 'L2_U07', name: 'じぶんのせいちょう', mode: 'LIFE_2_U07', sourceMode: 'LIFE_2_3' },
  ],
  3: [
    { id: 'S3_U01', name: 'しぜんのかんさつ', mode: 'SCIENCE_3_U01', sourceMode: 'SCIENCE_3_1' },
    { id: 'S3_U02', name: 'こん虫のせい長', mode: 'SCIENCE_3_U02', sourceMode: 'SCIENCE_3_1' },
    { id: 'S3_U03', name: 'しょくぶつのせい長', mode: 'SCIENCE_3_U03', sourceMode: 'SCIENCE_3_1' },
    { id: 'S3_U04', name: '太陽と地面', mode: 'SCIENCE_3_U04', sourceMode: 'SCIENCE_3_2' },
    { id: 'S3_U05', name: '光', mode: 'SCIENCE_3_U05', sourceMode: 'SCIENCE_3_2' },
    { id: 'S3_U06', name: '音', mode: 'SCIENCE_3_U06', sourceMode: 'SCIENCE_3_2' },
    { id: 'S3_U07', name: '風とゴムのはたらき', mode: 'SCIENCE_3_U07', sourceMode: 'SCIENCE_3_3' },
    { id: 'S3_U08', name: '電気の通り道', mode: 'SCIENCE_3_U08', sourceMode: 'SCIENCE_3_3' },
    { id: 'S3_U09', name: 'ものの重さ', mode: 'SCIENCE_3_U09', sourceMode: 'SCIENCE_3_3' },
    { id: 'S3_U10', name: 'じしゃく', mode: 'SCIENCE_3_U10', sourceMode: 'SCIENCE_3_3' },
  ],
  4: [
    { id: 'S4_U01', name: '天気と気温', mode: 'SCIENCE_4_U01', sourceMode: 'SCIENCE_4_2' },
    { id: 'S4_U02', name: '季節と生き物', mode: 'SCIENCE_4_U02', sourceMode: 'SCIENCE_4_1' },
    { id: 'S4_U03', name: '星と空', mode: 'SCIENCE_4_U03', sourceMode: 'SCIENCE_4_2' },
    { id: 'S4_U04', name: '月の動き', mode: 'SCIENCE_4_U04', sourceMode: 'SCIENCE_4_2' },
    { id: 'S4_U05', name: '電気のはたらき', mode: 'SCIENCE_4_U05', sourceMode: 'SCIENCE_4_3' },
    { id: 'S4_U06', name: '空気と水', mode: 'SCIENCE_4_U06', sourceMode: 'SCIENCE_4_3' },
    { id: 'S4_U07', name: 'とじこめた空気', mode: 'SCIENCE_4_U07', sourceMode: 'SCIENCE_4_3' },
    { id: 'S4_U08', name: '水のすがた', mode: 'SCIENCE_4_U08', sourceMode: 'SCIENCE_4_3' },
    { id: 'S4_U09', name: 'もののあたたまり方', mode: 'SCIENCE_4_U09', sourceMode: 'SCIENCE_4_3' },
  ],
  5: [
    { id: 'S5_U01', name: '天気の変化', mode: 'SCIENCE_5_U01', sourceMode: 'SCIENCE_5_2' },
    { id: 'S5_U02', name: '台風と天気', mode: 'SCIENCE_5_U02', sourceMode: 'SCIENCE_5_2' },
    { id: 'S5_U03', name: '植物の発芽と成長', mode: 'SCIENCE_5_U03', sourceMode: 'SCIENCE_5_1' },
    { id: 'S5_U04', name: '花から実へ', mode: 'SCIENCE_5_U04', sourceMode: 'SCIENCE_5_1' },
    { id: 'S5_U05', name: 'メダカのたんじょう', mode: 'SCIENCE_5_U05', sourceMode: 'SCIENCE_5_2' },
    { id: 'S5_U06', name: '人のたんじょう', mode: 'SCIENCE_5_U06', sourceMode: '__NO_SOURCE__' },
    { id: 'S5_U07', name: '流れる水のはたらき', mode: 'SCIENCE_5_U07', sourceMode: 'SCIENCE_5_2' },
    { id: 'S5_U08', name: '物のとけ方', mode: 'SCIENCE_5_U08', sourceMode: 'SCIENCE_5_3' },
    { id: 'S5_U09', name: '電磁石', mode: 'SCIENCE_5_U09', sourceMode: 'SCIENCE_5_3' },
  ],
  6: [
    { id: 'S6_U01', name: '物の燃え方', mode: 'SCIENCE_6_U01', sourceMode: 'SCIENCE_6_1' },
    { id: 'S6_U02', name: '植物のつくりとはたらき', mode: 'SCIENCE_6_U02', sourceMode: 'SCIENCE_6_1' },
    { id: 'S6_U03', name: '人の体のつくりとはたらき', mode: 'SCIENCE_6_U03', sourceMode: 'SCIENCE_6_1' },
    { id: 'S6_U04', name: '月と太陽', mode: 'SCIENCE_6_U04', sourceMode: '__NO_SOURCE__' },
    { id: 'S6_U05', name: 'てこ', mode: 'SCIENCE_6_U05', sourceMode: 'SCIENCE_6_2' },
    { id: 'S6_U06', name: '水よう液', mode: 'SCIENCE_6_U06', sourceMode: 'SCIENCE_6_3' },
    { id: 'S6_U07', name: '電気の利用', mode: 'SCIENCE_6_U07', sourceMode: 'SCIENCE_6_3' },
    { id: 'S6_U08', name: '土地のつくり', mode: 'SCIENCE_6_U08', sourceMode: 'SCIENCE_6_2' },
    { id: 'S6_U09', name: '生き物と環境', mode: 'SCIENCE_6_U09', sourceMode: 'SCIENCE_6_2' },
  ],
  7: [
    { id: 'S7_U01', name: '生物の観察と分類', mode: 'SCIENCE_7_U01', sourceMode: 'SCIENCE_7_1' },
    { id: 'S7_U02', name: '植物の体のつくりとはたらき', mode: 'SCIENCE_7_U02', sourceMode: 'SCIENCE_7_1' },
    { id: 'S7_U03', name: '動物の体のつくりとはたらき', mode: 'SCIENCE_7_U03', sourceMode: 'SCIENCE_7_1' },
    { id: 'S7_U04', name: '身のまわりの物質', mode: 'SCIENCE_7_U04', sourceMode: 'SCIENCE_7_1' },
    { id: 'S7_U05', name: '気体の性質', mode: 'SCIENCE_7_U05', sourceMode: 'SCIENCE_7_1' },
    { id: 'S7_U06', name: '水溶液の性質', mode: 'SCIENCE_7_U06', sourceMode: 'SCIENCE_7_1' },
    { id: 'S7_U07', name: '光', mode: 'SCIENCE_7_U07', sourceMode: 'SCIENCE_7_2' },
    { id: 'S7_U08', name: '音', mode: 'SCIENCE_7_U08', sourceMode: 'SCIENCE_7_2' },
    { id: 'S7_U09', name: '力と圧力', mode: 'SCIENCE_7_U09', sourceMode: 'SCIENCE_7_2' },
    { id: 'S7_U10', name: '大地の変化', mode: 'SCIENCE_7_U10', sourceMode: 'SCIENCE_7_3' },
    { id: 'S7_U11', name: '火山', mode: 'SCIENCE_7_U11', sourceMode: 'SCIENCE_7_3' },
    { id: 'S7_U12', name: '地震', mode: 'SCIENCE_7_U12', sourceMode: 'SCIENCE_7_3' },
    { id: 'S7_U13', name: '地層', mode: 'SCIENCE_7_U13', sourceMode: 'SCIENCE_7_3' },
  ],
  8: [
    { id: 'S8_U01', name: '生物と細胞', mode: 'SCIENCE_8_U01', sourceMode: 'SCIENCE_8_2' },
    { id: 'S8_U02', name: '植物の体のつくりとはたらき', mode: 'SCIENCE_8_U02', sourceMode: 'SCIENCE_8_2' },
    { id: 'S8_U03', name: '動物の体のつくりとはたらき', mode: 'SCIENCE_8_U03', sourceMode: 'SCIENCE_8_2' },
    { id: 'S8_U04', name: '化学変化', mode: 'SCIENCE_8_U04', sourceMode: 'SCIENCE_8_1' },
    { id: 'S8_U05', name: '原子と分子', mode: 'SCIENCE_8_U05', sourceMode: 'SCIENCE_8_1' },
    { id: 'S8_U06', name: '化学変化と質量', mode: 'SCIENCE_8_U06', sourceMode: 'SCIENCE_8_1' },
    { id: 'S8_U07', name: '電流', mode: 'SCIENCE_8_U07', sourceMode: 'SCIENCE_8_3' },
    { id: 'S8_U08', name: '電流と磁界', mode: 'SCIENCE_8_U08', sourceMode: 'SCIENCE_8_3' },
    { id: 'S8_U09', name: '天気と気象', mode: 'SCIENCE_8_U09', sourceMode: 'SCIENCE_8_3' },
    { id: 'S8_U10', name: '前線と天気', mode: 'SCIENCE_8_U10', sourceMode: 'SCIENCE_8_3' },
  ],
  9: [
    { id: 'S9_U01', name: '生物の成長と生殖', mode: 'SCIENCE_9_U01', sourceMode: 'SCIENCE_9_1' },
    { id: 'S9_U02', name: '遺伝', mode: 'SCIENCE_9_U02', sourceMode: 'SCIENCE_9_1' },
    { id: 'S9_U03', name: '生物のつながり', mode: 'SCIENCE_9_U03', sourceMode: 'SCIENCE_9_1' },
    { id: 'S9_U04', name: '化学変化とイオン', mode: 'SCIENCE_9_U04', sourceMode: 'SCIENCE_9_2' },
    { id: 'S9_U05', name: '酸とアルカリ', mode: 'SCIENCE_9_U05', sourceMode: 'SCIENCE_9_2' },
    { id: 'S9_U06', name: '中和', mode: 'SCIENCE_9_U06', sourceMode: 'SCIENCE_9_2' },
    { id: 'S9_U07', name: '力の合成と分解', mode: 'SCIENCE_9_U07', sourceMode: 'SCIENCE_9_1' },
    { id: 'S9_U08', name: '運動', mode: 'SCIENCE_9_U08', sourceMode: 'SCIENCE_9_1' },
    { id: 'S9_U09', name: '仕事とエネルギー', mode: 'SCIENCE_9_U09', sourceMode: 'SCIENCE_9_1' },
    { id: 'S9_U10', name: '地球と宇宙', mode: 'SCIENCE_9_U10', sourceMode: 'SCIENCE_9_3' },
    { id: 'S9_U11', name: '太陽系', mode: 'SCIENCE_9_U11', sourceMode: 'SCIENCE_9_3' },
    { id: 'S9_U12', name: '星の動き', mode: 'SCIENCE_9_U12', sourceMode: 'SCIENCE_9_3' },
  ],
};
