export interface SocialUnitOption {
  id: string;
  name: string;
  mode: string;
  sourceMode: string;
}

export const SOCIAL_GRADE_UNITS: Record<number, SocialUnitOption[]> = {
  3: [
    { id: 'SO3_U01', name: 'わたしたちの町', mode: 'SOCIAL_3_U01', sourceMode: 'SOCIAL_3_1' },
    { id: 'SO3_U02', name: '地図の見方', mode: 'SOCIAL_3_U02', sourceMode: 'SOCIAL_3_1' },
    { id: 'SO3_U03', name: '土地のようす', mode: 'SOCIAL_3_U03', sourceMode: 'SOCIAL_3_1' },
    { id: 'SO3_U04', name: '町ではたらく人', mode: 'SOCIAL_3_U04', sourceMode: 'SOCIAL_3_2' },
    { id: 'SO3_U05', name: '商店のしごと', mode: 'SOCIAL_3_U05', sourceMode: 'SOCIAL_3_2' },
    { id: 'SO3_U06', name: '農家のしごと', mode: 'SOCIAL_3_U06', sourceMode: 'SOCIAL_3_2' },
    { id: 'SO3_U07', name: '工場のしごと', mode: 'SOCIAL_3_U07', sourceMode: 'SOCIAL_3_2' },
    { id: 'SO3_U08', name: '交通のはたらき', mode: 'SOCIAL_3_U08', sourceMode: 'SOCIAL_3_2' },
    { id: 'SO3_U09', name: '市のようすのうつりかわり', mode: 'SOCIAL_3_U09', sourceMode: 'SOCIAL_3_3' },
  ],
  4: [
    { id: 'SO4_U01', name: '都道府県', mode: 'SOCIAL_4_U01', sourceMode: 'SOCIAL_4_1' },
    { id: 'SO4_U02', name: '日本の地形', mode: 'SOCIAL_4_U02', sourceMode: 'SOCIAL_4_1' },
    { id: 'SO4_U03', name: '気候', mode: 'SOCIAL_4_U03', sourceMode: 'SOCIAL_4_1' },
    { id: 'SO4_U04', name: '水のしごと', mode: 'SOCIAL_4_U04', sourceMode: 'SOCIAL_4_2' },
    { id: 'SO4_U05', name: 'ごみのしょり', mode: 'SOCIAL_4_U05', sourceMode: 'SOCIAL_4_2' },
    { id: 'SO4_U06', name: '災害とくらし', mode: 'SOCIAL_4_U06', sourceMode: 'SOCIAL_4_2' },
    { id: 'SO4_U07', name: '地図帳の使い方', mode: 'SOCIAL_4_U07', sourceMode: 'SOCIAL_4_1' },
    { id: 'SO4_U08', name: '県のようす', mode: 'SOCIAL_4_U08', sourceMode: 'SOCIAL_4_1' },
    { id: 'SO4_U09', name: '伝統文化', mode: 'SOCIAL_4_U09', sourceMode: 'SOCIAL_4_3' },
  ],
  5: [
    { id: 'SO5_U01', name: '日本の国土', mode: 'SOCIAL_5_U01', sourceMode: 'SOCIAL_5_1' },
    { id: 'SO5_U02', name: '日本の気候', mode: 'SOCIAL_5_U02', sourceMode: 'SOCIAL_5_1' },
    { id: 'SO5_U03', name: '農業', mode: 'SOCIAL_5_U03', sourceMode: 'SOCIAL_5_1' },
    { id: 'SO5_U04', name: '水産業', mode: 'SOCIAL_5_U04', sourceMode: 'SOCIAL_5_1' },
    { id: 'SO5_U05', name: '工業', mode: 'SOCIAL_5_U05', sourceMode: 'SOCIAL_5_2' },
    { id: 'SO5_U06', name: '貿易', mode: 'SOCIAL_5_U06', sourceMode: 'SOCIAL_5_2' },
    { id: 'SO5_U07', name: '情報産業', mode: 'SOCIAL_5_U07', sourceMode: 'SOCIAL_5_3' },
    { id: 'SO5_U08', name: '環境問題', mode: 'SOCIAL_5_U08', sourceMode: 'SOCIAL_5_3' },
    { id: 'SO5_U09', name: '食料問題', mode: 'SOCIAL_5_U09', sourceMode: 'SOCIAL_5_3' },
  ],
  6: [
    { id: 'SO6_U01', name: '日本の歴史（縄文・弥生）', mode: 'SOCIAL_6_U01', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U02', name: '古墳時代', mode: 'SOCIAL_6_U02', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U03', name: '奈良時代', mode: 'SOCIAL_6_U03', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U04', name: '平安時代', mode: 'SOCIAL_6_U04', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U05', name: '鎌倉時代', mode: 'SOCIAL_6_U05', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U06', name: '室町時代', mode: 'SOCIAL_6_U06', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U07', name: '安土桃山時代', mode: 'SOCIAL_6_U07', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U08', name: '江戸時代', mode: 'SOCIAL_6_U08', sourceMode: 'SOCIAL_6_1' },
    { id: 'SO6_U09', name: '明治時代', mode: 'SOCIAL_6_U09', sourceMode: 'SOCIAL_6_2' },
    { id: 'SO6_U10', name: '大正時代', mode: 'SOCIAL_6_U10', sourceMode: 'SOCIAL_6_2' },
    { id: 'SO6_U11', name: '昭和時代', mode: 'SOCIAL_6_U11', sourceMode: 'SOCIAL_6_2' },
    { id: 'SO6_U12', name: '日本国憲法', mode: 'SOCIAL_6_U12', sourceMode: 'SOCIAL_6_3' },
    { id: 'SO6_U13', name: '国会', mode: 'SOCIAL_6_U13', sourceMode: 'SOCIAL_6_3' },
    { id: 'SO6_U14', name: '内閣', mode: 'SOCIAL_6_U14', sourceMode: 'SOCIAL_6_3' },
    { id: 'SO6_U15', name: '裁判所', mode: 'SOCIAL_6_U15', sourceMode: 'SOCIAL_6_3' },
    { id: 'SO6_U16', name: '地方自治', mode: 'SOCIAL_6_U16', sourceMode: 'SOCIAL_6_3' },
    { id: 'SO6_U17', name: '国際社会', mode: 'SOCIAL_6_U17', sourceMode: 'SOCIAL_6_3' },
  ],
  7: [
    { id: 'SO7_U01', name: '世界の地域', mode: 'SOCIAL_7_U01', sourceMode: 'SOCIAL_7_1' },
    { id: 'SO7_U02', name: '世界の気候', mode: 'SOCIAL_7_U02', sourceMode: 'SOCIAL_7_1' },
    { id: 'SO7_U03', name: '世界の人口', mode: 'SOCIAL_7_U03', sourceMode: 'SOCIAL_7_1' },
    { id: 'SO7_U04', name: '世界の産業', mode: 'SOCIAL_7_U04', sourceMode: 'SOCIAL_7_1' },
    { id: 'SO7_U05', name: 'アジア', mode: 'SOCIAL_7_U05', sourceMode: 'SOCIAL_7_2' },
    { id: 'SO7_U06', name: 'ヨーロッパ', mode: 'SOCIAL_7_U06', sourceMode: 'SOCIAL_7_2' },
    { id: 'SO7_U07', name: 'アフリカ', mode: 'SOCIAL_7_U07', sourceMode: 'SOCIAL_7_2' },
    { id: 'SO7_U08', name: '北アメリカ', mode: 'SOCIAL_7_U08', sourceMode: 'SOCIAL_7_2' },
    { id: 'SO7_U09', name: '南アメリカ', mode: 'SOCIAL_7_U09', sourceMode: 'SOCIAL_7_2' },
    { id: 'SO7_U10', name: 'オセアニア', mode: 'SOCIAL_7_U10', sourceMode: 'SOCIAL_7_2' },
    { id: 'SO7_U11', name: '日本の地域', mode: 'SOCIAL_7_U11', sourceMode: 'SOCIAL_7_3' },
    { id: 'SO7_U12', name: '日本の自然', mode: 'SOCIAL_7_U12', sourceMode: 'SOCIAL_7_3' },
    { id: 'SO7_U13', name: '日本の人口', mode: 'SOCIAL_7_U13', sourceMode: 'SOCIAL_7_3' },
    { id: 'SO7_U14', name: '日本の産業', mode: 'SOCIAL_7_U14', sourceMode: 'SOCIAL_7_3' },
  ],
  8: [
    { id: 'SO8_U01', name: '古代文明', mode: 'SOCIAL_8_U01', sourceMode: 'SOCIAL_8_1' },
    { id: 'SO8_U02', name: 'ギリシャ・ローマ', mode: 'SOCIAL_8_U02', sourceMode: 'SOCIAL_8_1' },
    { id: 'SO8_U03', name: '日本の古代', mode: 'SOCIAL_8_U03', sourceMode: 'SOCIAL_8_1' },
    { id: 'SO8_U04', name: '日本の中世', mode: 'SOCIAL_8_U04', sourceMode: 'SOCIAL_8_1' },
    { id: 'SO8_U05', name: '日本の近世', mode: 'SOCIAL_8_U05', sourceMode: 'SOCIAL_8_2' },
    { id: 'SO8_U06', name: '欧米の近代化', mode: 'SOCIAL_8_U06', sourceMode: 'SOCIAL_8_2' },
    { id: 'SO8_U07', name: '明治維新', mode: 'SOCIAL_8_U07', sourceMode: 'SOCIAL_8_2' },
    { id: 'SO8_U08', name: '日本の近代化', mode: 'SOCIAL_8_U08', sourceMode: 'SOCIAL_8_2' },
    { id: 'SO8_U09', name: '世界大戦', mode: 'SOCIAL_8_U09', sourceMode: 'SOCIAL_8_3' },
    { id: 'SO8_U10', name: '現代の日本', mode: 'SOCIAL_8_U10', sourceMode: 'SOCIAL_8_3' },
  ],
  9: [
    { id: 'SO9_U01', name: '現代社会', mode: 'SOCIAL_9_U01', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U02', name: '人権', mode: 'SOCIAL_9_U02', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U03', name: '民主主義', mode: 'SOCIAL_9_U03', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U04', name: '日本国憲法', mode: 'SOCIAL_9_U04', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U05', name: '国会', mode: 'SOCIAL_9_U05', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U06', name: '内閣', mode: 'SOCIAL_9_U06', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U07', name: '裁判所', mode: 'SOCIAL_9_U07', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U08', name: '地方自治', mode: 'SOCIAL_9_U08', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U09', name: '選挙', mode: 'SOCIAL_9_U09', sourceMode: 'SOCIAL_9_1' },
    { id: 'SO9_U10', name: '税金', mode: 'SOCIAL_9_U10', sourceMode: 'SOCIAL_9_2' },
    { id: 'SO9_U11', name: '市場経済', mode: 'SOCIAL_9_U11', sourceMode: 'SOCIAL_9_2' },
    { id: 'SO9_U12', name: '金融', mode: 'SOCIAL_9_U12', sourceMode: 'SOCIAL_9_2' },
    { id: 'SO9_U13', name: '労働', mode: 'SOCIAL_9_U13', sourceMode: 'SOCIAL_9_2' },
    { id: 'SO9_U14', name: '社会保障', mode: 'SOCIAL_9_U14', sourceMode: 'SOCIAL_9_2' },
    { id: 'SO9_U15', name: '国際社会', mode: 'SOCIAL_9_U15', sourceMode: 'SOCIAL_9_2' },
    { id: 'SO9_U16', name: '国際協力', mode: 'SOCIAL_9_U16', sourceMode: 'SOCIAL_9_2' },
  ],
};
